# action.yml
name: 'Data Theorem Mobile Secure'
description: |
  Uploads your pre-production mobile app binaries to Data Theorem for scanning.
inputs:
  DT_UPLOAD_API_KEY:
    description: 'Data Theorem upload API key'
    required: true
  UPLOAD_BINARY_PATH:
    description: 'Path to the app to upload (can be a glob pattern like `/app/build/outputs/apk/debug/*.apk`)'
    required: true
runs:
  using: 'node16'
  main: 'main.js'
branding:
  color: 'blue'
  icon: 'arrow-up-circle'